heat_template_version: pike

description: >
  OpenStack containerized Nova Compute service

parameters:
  DockerNovaComputeImage:
    description: image
    type: string
  DockerNovaLibvirtConfigImage:
    description: The container image to use for the nova_libvirt config_volume
    type: string
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  DockerNovaMigrationSshdPort:
    default: 2022
    description: Port that dockerized nova migration target sshd service
                 binds to.
    type: number
  UpgradeLevelNovaCompute:
    type: string
    description: Nova Compute upgrade level
    default: ''
  UpgradeRemoveUnusedPackages:
    default: false
    description: Remove package if the service is being disabled during upgrade
    type: boolean
  CephClientUserName:
    default: openstack
    type: string
  NovaComputeOptVolumes:
    default: []
    description: list of optional vo
    type: comma_delimited_list
  NovaComputeOptEnvVars:
    default: []
    description: list of optional en
    type: comma_delimited_list

resources:

  ContainersCommon:
    type: ./containers-common.yaml

  MySQLClient:
    type: ../../puppet/services/database/mysql-client.yaml

  NovaComputeCommon:
    type: ./nova-compute-common.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

  NovaComputeBase:
    type: ../../puppet/services/nova-compute.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

outputs:
  role_data:
    description: Role data for the Nova Compute service.
    value:
      service_name: {get_attr: [NovaComputeBase, role_data, service_name]}
      cellv2_discovery: true
      config_settings:
        get_attr: [NovaComputeBase, role_data, config_settings]
      logging_source: {get_attr: [NovaComputeBase, role_data, logging_source]}
      logging_groups: {get_attr: [NovaComputeBase, role_data, logging_groups]}
      step_config: &step_config
        list_join:
          - "\n"
          - - {get_attr: [NovaComputeBase, role_data, step_config]}
            - {get_attr: [MySQLClient, role_data, step_config]}
      puppet_config:
        config_volume: nova_libvirt
        puppet_tags: nova_config,nova_paste_api_ini
        step_config: *step_config
        config_image: {get_param: DockerNovaLibvirtConfigImage}
      kolla_config:
        /var/lib/kolla/config_files/nova_compute.json:
          command: /usr/bin/nova-compute --config-file /etc/nova/nova.conf --config-file /etc/nova/rootwrap.conf
          config_files:
            - source: "/var/lib/kolla/config_files/src/*"
              dest: "/"
              merge: true
              preserve_properties: true
            - source: "/var/lib/kolla/config_files/src-iscsid/*"
              dest: "/etc/iscsi/"
              merge: true
              preserve_properties: true
            - source: "/var/lib/kolla/config_files/src-ceph/"
              dest: "/etc/ceph/"
              merge: true
              preserve_properties: true
          permissions:
            - path: /var/log/nova
              owner: nova:nova
              recurse: true
            - path:
                str_replace:
                  template: /etc/ceph/ceph.client.USER.keyring
                  params:
                    USER: {get_param: CephClientUserName}
              owner: nova:nova
              perm: '0600'
      docker_config_scripts: {get_attr: [NovaComputeCommon, docker_config_scripts]}
      docker_config:
        step_3:
          nova_statedir_owner:
            image: &nova_compute_image {get_param: DockerNovaComputeImage}
            user: root
            privileged: false
            detach: false
            volumes:
              - /var/lib/nova:/var/lib/nova:shared
              - /var/lib/docker-config-scripts/:/docker-config-scripts/
            command: "/docker-config-scripts/nova_statedir_ownership.py"
        step_4:
          nova_compute:
            image: *nova_compute_image
            ipc: host
            net: host
            privileged: true
            user: nova
            restart: always
            volumes:
              list_concat:
                - {get_attr: [ContainersCommon, volumes]}
                - {get_param: NovaComputeOptVolumes}
                -
                  - /var/lib/kolla/config_files/nova_compute.json:/var/lib/kolla/config_files/config.json:ro
                  - /var/lib/config-data/puppet-generated/nova_libvirt/:/var/lib/kolla/config_files/src:ro
                  - /etc/iscsi:/var/lib/kolla/config_files/src-iscsid:ro
                  - /etc/ceph:/var/lib/kolla/config_files/src-ceph:ro
                  - /dev:/dev
                  - /lib/modules:/lib/modules:ro
                  - /run:/run
                  - /var/lib/nova:/var/lib/nova:shared
                  - /var/lib/libvirt:/var/lib/libvirt
                  - /var/log/containers/nova:/var/log/nova
                  - /sys/class/net:/sys/class/net
                  - /sys/bus/pci:/sys/bus/pci
            environment:
              list_concat:
                - {get_param: NovaComputeOptEnvVars}
                -
                  - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      host_prep_tasks:
        - name: create persistent directories
          file:
            path: "{{ item }}"
            state: directory
          with_items:
            - /var/log/containers/nova
            - /var/lib/nova
            - /var/lib/nova/instances
            - /var/lib/libvirt
        - name: nova logs readme
          copy:
            dest: /var/log/nova/readme.txt
            content: |
              Log files from nova containers can be found under
              /var/log/containers/nova and /var/log/containers/httpd/nova-*.
          ignore_errors: true
        - name: ensure ceph configurations exist
          file:
            path: /etc/ceph
            state: directory
      upgrade_tasks:
        - name: Check if nova_compute is deployed
          command: systemctl is-enabled --quiet openstack-nova-compute
          tags: common
          ignore_errors: True
          register: nova_compute_enabled
        - name: Set compute upgrade level to auto
          tags: step1
          ini_file:
            str_replace:
              template: "dest=/etc/nova/nova.conf section=upgrade_levels option=compute value=LEVEL"
              params:
                LEVEL: {get_param: UpgradeLevelNovaCompute}
        - name: "PreUpgrade step0,validation: Check service openstack-nova-compute is running"
          command: systemctl is-active --quiet openstack-nova-compute
          tags: step0,validation
          when: nova_compute_enabled.rc == 0
        - name: Stop and disable nova-compute service
          tags: step2
          when: nova_compute_enabled.rc == 0
          service: name=openstack-nova-compute state=stopped enabled=no
        - name: Set upgrade marker in nova statedir
          tags: step2
          when: nova_compute_enabled.rc == 0
          file: path=/var/lib/nova/upgrade_marker state=touch owner=nova group=nova
        - name: Remove openstack-nova-compute package if operator requests it
          yum: name=openstack-nova-compute state=removed
          tags: step2
          ignore_errors: True
          when: {get_param: UpgradeRemoveUnusedPackages}
