#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist)
  #OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/compute.yaml
  #OS::TripleO::Computesriov::Net::SoftwareConfig: /home/stack/templates/nic-configs/computesriov.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
  #OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/swift-storage.yaml
  #OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/ceph-storage.yaml  
  #OS::TripleO::HPComputesriov::Net::SoftwareConfig: /home/stack/templates/nic-configs/hp-computesriov.yaml
  #OS::TripleO::DellComputesriov::Net::SoftwareConfig: /home/stack/templates/nic-configs/dell-computesriov.yaml
  OS::TripleO::HPCompute::Net::SoftwareConfig: /home/stack/templates/nic-configs/hp-compute.yaml
  OS::TripleO::DellCompute::Net::SoftwareConfig: /home/stack/templates/nic-configs/dell-compute.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '23'
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.25.14
  EC2MetadataIp: 192.168.25.14  # Generally the IP of the Undercloud
  # Customize the IP subnets to match the local environment
  InternalApiNetCidr: 10.92.0.0/16
  StorageNetCidr: 10.93.0.0/16
  StorageMgmtNetCidr: 10.94.0.0/16
  TenantNetCidr: 10.95.0.0/16
  ExternalNetCidr: 10.11.0.0/23
  # Customize the VLAN IDs to match the local environment
  InternalApiNetworkVlanID: 92
  StorageNetworkVlanID: 93
  StorageMgmtNetworkVlanID: 94
  TenantNetworkVlanID: 95
  ExternalNetworkVlanID: 96
  # Customize the IP ranges on each network to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '10.92.0.10', 'end': '10.92.0.200'}]
  StorageAllocationPools: [{'start': '10.93.0.10', 'end': '10.93.0.200'}]
  StorageMgmtAllocationPools: [{'start': '10.94.0.10', 'end': '10.94.0.200'}]
  TenantAllocationPools: [{'start': '10.95.0.10', 'end': '10.95.0.200'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '10.146.94.100', 'end': '10.146.94.200'}]
  # Gateway router for the external network
  ExternalInterfaceDefaultRoute: 10.146.95.254
  # Uncomment if using the Management Network (see network-management.yaml)
  #ManagementNetCidr: 10.146.92.0/24
  #ManagementAllocationPools: [{'start': '10.146.92.120', 'end', '10.146.92.180'}]
  # Use either this parameter or ControlPlaneDefaultRoute in the NIC templates
  #ManagementInterfaceDefaultRoute: 10.146.92.254
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["172.23.193.182","172.23.225.182"]
  # Set to empty string to enable multiple external networks or VLANs
  NeutronExternalNetworkBridge: "''"
  # The tunnel type for the tenant network (vxlan or gre). Set to '' to disable tunneling.
  NeutronTunnelTypes: 'vxlan'
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  #BondInterfaceOvsOptions: "bond_mode=active-backup"
  ###########################################################################
  #SR-IOV
  ###########################################################################  
  ComputeKernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=12 intel_iommu=on iommu=pt"  
  NeutronNetworkType: 'vlan,vxlan'
  NovaReservedHostMemory: 4096    
  NovaVcpuPinSet: ""
  HostIsolatedCoreList: ""
