resource_registry:
  OS::TripleO::Server: /usr/share/openstack-tripleo-heat-templates/deployed-server/deployed-server.yaml
  OS::TripleO::DeployedServer::ControlPlanePort: /usr/share/openstack-tripleo-heat-templates/deployed-server/deployed-neutron-port.yaml
  OS::TripleO::DeployedServer::Bootstrap: OS::Heat::None

  # Network configuration assignments for the Controller Role
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/virtcontroller4.yaml
  # Network configuration assignments for the ComputeVirt Role
  OS::TripleO::ComputeVirt::Net::SoftwareConfig: /home/stack/templates/virtcompute4.yaml
  # Network configuration assignments for the ComputeMetal Role
  OS::TripleO::ComputeMetal::Net::SoftwareConfig: /home/stack/templates/metalcompute4.yaml
  # Network configuration assignments for the BlockStorage
  # OS::TripleO::BlockStorage::Net::SoftwareConfig: /usr/share/openstack-tripleo-heat-templates/network/config/multiple-nics-vlans/cinder-storage.yaml
  # Network configuration assignments for the ObjectStorage
  # OS::TripleO::ObjectStorage::Net::SoftwareConfig: /usr/share/openstack-tripleo-heat-templates/network/config/multiple-nics-vlans/swift-storage.yaml
  # Network configuration assignments for the CephStorage
  # OS::TripleO::CephStorage::Net::SoftwareConfig: /usr/share/openstack-tripleo-heat-templates/network/config/multiple-nics-vlans/ceph-storage.yaml


parameter_defaults:
  # NeutronOVSFirewallDriver: noop
  CloudDomain: splab.pdsea.f5net.com
  EnablePackageInstall: True
  NeutronPublicInterface: ens192
  ControlPlaneDefaultRoute: 192.168.60.11
  # EC2MetadataIp: 192.168.60.25
  HostnameMap:
    thomas01-controller-0: controller1601
    thomas01-controller-1: controller1602
    thomas01-controller-2: controller1603
    thomas01-computevirt-0: computevirt1601
    thomas01-computemetal-0: computemetal1601
  DeployedServerPortMap:
    controller1601-ctlplane:
      fixed_ips:
        - ip_address: 192.168.60.85
      subnets:
        - cidr: 192.168.60.0/24
      network:
        tags:
          - 192.168.60.0/24
    controller1602-ctlplane:
      fixed_ips:
        - ip_address: 192.168.60.87
      subnets:
        - cidr: 192.168.60.0/24
      network:
        tags:
          - 192.168.60.0/24
    controller1603-ctlplane:
      fixed_ips:
        - ip_address: 192.168.60.88
      subnets:
        - cidr: 192.168.60.0/24
      network:
        tags:
          - 192.168.60.0/24
    computevirt1601-ctlplane:
      fixed_ips:
        - ip_address: 192.168.60.86
      subnets:
        - cidr: 192.168.60.0/24
      network:
        tags:
          - 192.168.60.0/24
    computemetal1601-ctlplane: # m-d-r640-03.splab.pdsea.f5net.com
      fixed_ips:
        - ip_address: 192.168.60.91
      subnets:
        - cidr: 192.168.60.0/24
      network:
        tags:
          - 192.168.60.0/24
  
  
  # This section is where deployment-specific configuration is done
  #
  # NOTE: (Since Rocky)
  # ControlPlaneSubnetCidr: It is no longer a requirement to provide the
  #                         parameter. The attribute is resolved from the
  #                         ctlplane subnet(s).
  # ControlPlaneDefaultRoute: It is no longer a requirement to provide this
  #                           parameter. The attribute is resolved from the
  #                           ctlplane subnet(s).
  # EC2MetadataIp: It is no longer a requirement to provide this parameter. The
  #                attribute is resolved from the ctlplane subnet(s).
  #
  # Customize the IP subnets to match the local environment
  StorageNetCidr: '10.12.0.0/24'
  StorageMgmtNetCidr: '10.94.0.0/16'
  InternalApiNetCidr: '10.92.0.0/16'
  TenantNetCidr: '10.95.0.0/16'
  ExternalNetCidr: '10.144.184.0/22'
  # Customize the VLAN IDs to match the local environment
  StorageNetworkVlanID: 12
  StorageMgmtNetworkVlanID: 93
  InternalApiNetworkVlanID: 94
  TenantNetworkVlanID: 95
  ExternalNetworkVlanID: 10
  StorageAllocationPools: [{'start': '10.12.0.50', 'end': '10.12.0.99'}]
  StorageMgmtAllocationPools: [{'start': '10.94.1.100', 'end': '10.94.1.200'}]
  InternalApiAllocationPools: [{'start': '10.92.1.100', 'end': '10.92.1.200'}]
  TenantAllocationPools: [{'start': '10.95.1.100', 'end': '10.95.1.200'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '10.144.184.20', 'end': '10.144.184.25'}]
  # Gateway routers for routable networks
  ExternalInterfaceDefaultRoute: '10.144.187.254'
  ### Custom VIP addresses
  # ControlFixedIPs: [{'ip_address':'192.168.201.101'}]
  InternalApiVirtualFixedIPs: [{'ip_address':'10.92.1.120'}]
  PublicVirtualFixedIPs: [{'ip_address':'10.144.184.11'}]
  StorageVirtualFixedIPs: [{'ip_address':'10.12.0.78'}]
  StorageMgmtVirtualFixedIPs: [{'ip_address':'10.94.1.111'}]
  # RedisVirtualFixedIPs: [{'ip_address':'172.16.0.8'}]

  # Customize the IP subnet to match the local environment
  ManagementNetCidr: '192.168.60.0/24'
  # Customize the IP range to use for static IPs and VIPs
  ManagementAllocationPools: [{'start': '192.168.60.240', 'end': '192.168.60.250'}]
  # Gateway router for routable networks
  ManagementInterfaceDefaultRoute: '192.168.60.11'
  # Customize the VLAN ID to match the local environment
  ManagementNetworkVlanID: 90
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["172.27.1.1","172.27.2.1"]
  # List of Neutron network types for tenant networks (will be used in order)
  # NeutronNetworkType: 'vlan'
  # The tunnel type for the tenant network (vxlan or gre). Set to '' to disable tunneling.
  # NeutronTunnelTypes: 'vxlan'
  NeutronBridgeMappings:
    - float:br-ex
  # Neutron VLAN ranges per network, for example 'datacentre:1:499,tenant:500:1000':
  NeutronNetworkVLANRanges: 
    - float:10:10
  NeutronFlatNetworks: "float"
  # NeutronExternalNetworkBridge: "''"
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  # for Linux bonds w/LACP, or "bond_mode=active-backup" for OVS active/backup.
  BondInterfaceOvsOptions: "bond_mode=balance-slb lacp=off"
  ComputeVirtExtraConfig:        
    nova::disk_allocation_ratio: 4.0
  ComputeVirtSchedulerHints:
    'capabilities:profile': 'compute-%index%'
  ComputeMetalExtraConfig:        
    nova::disk_allocation_ratio: 4.0
  ComputeMetalSchedulerHints:
    'capabilities:profile': 'compute-%index%'
  TimeZone: 'America/Los_Angeles'
  ControllerCount: 3
  ComputeVirtCount: 1
  ComputeMetalCount: 0
  NetworkDeploymentActions: ['CREATE','UPDATE']