resource_registry:
  OS::TripleO::Server: /usr/share/openstack-tripleo-heat-templates/deployed-server/deployed-server.yaml
  OS::TripleO::DeployedServer::ControlPlanePort: /usr/share/openstack-tripleo-heat-templates/deployed-server/deployed-neutron-port.yaml
  OS::TripleO::DeployedServer::Bootstrap: OS::Heat::None

  # Network configuration assignments for the Controller Role
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/virtcontroller4.yaml
  # Network configuration assignments for the ComputeVirt Role
  OS::TripleO::ComputeVirt::Net::SoftwareConfig: /home/stack/templates/virtcompute4.yaml
  # Network configuration assignments for the ComputeMetal Role
  OS::TripleO::ComputeMetal::Net::SoftwareConfig: /home/stack/templates/metalcompute4.yaml
  # Network configuration assignments for the BlockStorage
  # OS::TripleO::BlockStorage::Net::SoftwareConfig: /usr/share/openstack-tripleo-heat-templates/network/config/multiple-nics-vlans/cinder-storage.yaml
  # Network configuration assignments for the ObjectStorage
  # OS::TripleO::ObjectStorage::Net::SoftwareConfig: /usr/share/openstack-tripleo-heat-templates/network/config/multiple-nics-vlans/swift-storage.yaml
  # Network configuration assignments for the CephStorage
  # OS::TripleO::CephStorage::Net::SoftwareConfig: /usr/share/openstack-tripleo-heat-templates/network/config/multiple-nics-vlans/ceph-storage.yaml


parameter_defaults:
  # NeutronOVSFirewallDriver: noop
  CloudDomain: amcs.com
  EnablePackageInstall: True
  NeutronPublicInterface: ens224
  ControlPlaneDefaultRoute: 192.168.50.11
  # EC2MetadataIp: 192.168.50.25
  HostnameMap:
    thomas01-controller-0: os16controller01
    thomas01-controller-1: os16controller02
    thomas01-controller-2: os16controller03
    thomas01-computevirt-0: os16computevirt01
    thomas01-computemetal-0: os16computemetal01
  DeployedServerPortMap:
    os16controller01-ctlplane:
      fixed_ips:
        - ip_address: 192.168.50.33
      subnets:
        - cidr: 192.168.50.0/24
      network:
        tags:
          - 192.168.50.0/24
    os16controller02-ctlplane:
      fixed_ips:
        - ip_address: 192.168.50.34
      subnets:
        - cidr: 192.168.50.0/24
      network:
        tags:
          - 192.168.50.0/24
    os16controller03-ctlplane:
      fixed_ips:
        - ip_address: 192.168.50.35
      subnets:
        - cidr: 192.168.50.0/24
      network:
        tags:
          - 192.168.50.0/24
    os16computevirt01-ctlplane:
      fixed_ips:
        - ip_address: 192.168.50.36
      subnets:
        - cidr: 192.168.50.0/24
      network:
        tags:
          - 192.168.50.0/24
    os16computemetal01-ctlplane:
      fixed_ips:
        - ip_address: 192.168.50.37
      subnets:
        - cidr: 192.168.50.0/24
      network:
        tags:
          - 192.168.50.0/24
  
  
  # This section is where deployment-specific configuration is done
  #
  # NOTE: (Since Rocky)
  # ControlPlaneSubnetCidr: It is no longer a requirement to provide the
  #                         parameter. The attribute is resolved from the
  #                         ctlplane subnet(s).
  # ControlPlaneDefaultRoute: It is no longer a requirement to provide this
  #                           parameter. The attribute is resolved from the
  #                           ctlplane subnet(s).
  # EC2MetadataIp: It is no longer a requirement to provide this parameter. The
  #                attribute is resolved from the ctlplane subnet(s).
  #
  # Customize the IP subnets to match the local environment
  StorageNetCidr: '192.168.2.0/24'
  StorageMgmtNetCidr: '10.94.0.0/16'
  InternalApiNetCidr: '10.92.0.0/16'
  TenantNetCidr: '10.95.0.0/16'
  ExternalNetCidr: '192.168.3.0/24'
  # Customize the VLAN IDs to match the local environment
  StorageNetworkVlanID: 200
  StorageMgmtNetworkVlanID: 93
  InternalApiNetworkVlanID: 94
  TenantNetworkVlanID: 95
  ExternalNetworkVlanID: 300
  StorageAllocationPools: [{'start': '192.168.2.50', 'end': '192.168.2.99'}]
  StorageMgmtAllocationPools: [{'start': '10.94.1.100', 'end': '10.94.1.200'}]
  InternalApiAllocationPools: [{'start': '10.92.1.100', 'end': '10.92.1.200'}]
  TenantAllocationPools: [{'start': '10.95.1.100', 'end': '10.95.1.200'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '192.168.3.220', 'end': '192.168.3.225'}]
  # Gateway routers for routable networks
  ExternalInterfaceDefaultRoute: '192.168.3.1'
  ### Custom VIP addresses
  # ControlFixedIPs: [{'ip_address':'192.168.201.101'}]
  InternalApiVirtualFixedIPs: [{'ip_address':'10.92.1.120'}]
  PublicVirtualFixedIPs: [{'ip_address':'192.168.3.219'}]
  StorageVirtualFixedIPs: [{'ip_address':'192.168.2.78'}]
  StorageMgmtVirtualFixedIPs: [{'ip_address':'10.94.1.111'}]
  # RedisVirtualFixedIPs: [{'ip_address':'172.16.0.8'}]

  # Customize the IP subnet to match the local environment
  ManagementNetCidr: '192.168.50.0/24'
  # Customize the IP range to use for static IPs and VIPs
  ManagementAllocationPools: [{'start': '192.168.50.240', 'end': '192.168.50.250'}]
  # Gateway router for routable networks
  ManagementInterfaceDefaultRoute: '192.168.50.11'
  # Customize the VLAN ID to match the local environment
  ManagementNetworkVlanID: 350
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["192.168.5.16","192.168.5.15"]
  # List of Neutron network types for tenant networks (will be used in order)
  # NeutronNetworkType: 'vlan'
  # The tunnel type for the tenant network (vxlan or gre). Set to '' to disable tunneling.
  # NeutronTunnelTypes: 'vxlan'
  NeutronBridgeMappings:
    - float:br-ex
  # Neutron VLAN ranges per network, for example 'datacentre:1:499,tenant:500:1000':
  NeutronNetworkVLANRanges: 
    - float:300:300
  NeutronFlatNetworks: "float"
  # NeutronExternalNetworkBridge: "''"
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  # for Linux bonds w/LACP, or "bond_mode=active-backup" for OVS active/backup.
  BondInterfaceOvsOptions: "bond_mode=active-backup"
  ComputeVirtExtraConfig:        
    nova::disk_allocation_ratio: 4.0
  ComputeVirtSchedulerHints:
    'capabilities:profile': 'compute-%index%'
  ComputeMetalExtraConfig:        
    nova::disk_allocation_ratio: 4.0
  ComputeMetalSchedulerHints:
    'capabilities:profile': 'compute-%index%'
  TimeZone: 'America/Los_Angeles'
  ControllerCount: 3
  ComputeVirtCount: 1
  ComputeMetalCount: 1
  NetworkDeploymentActions: ['CREATE','UPDATE']