- name: Create /var/lib/container-config-scripts
  become: true
  file:
    path: /var/lib/container-config-scripts
    state: directory
    setype: svirt_sandbox_file_t
  tags:
    - container_config_scripts

- name: Write container config scripts
  become: true
  no_log: True
  tripleo_container_config_scripts:
    config_data: "{{ lookup('file', tripleo_role_name + '/container_config_scripts.yaml', errors='ignore') | default({}, True) | from_yaml }}"
    config_dir: /var/lib/container-config-scripts
  tags:
    - container_config_scripts
