heat_template_version: rocky

description: >
  OpenStack Barbican client configuration

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json

outputs:
  role_data:
    description: Role data for the Barbican client.
    value:
      service_name: barbican_client
      service_config_settings:
        nova_compute:
          nova::compute::keymgr_backend: barbican
          nova::compute::barbican_endpoint:
            get_param: [EndpointMap, BarbicanInternal, uri]
          nova::compute::barbican_auth_endpoint:
            get_param: [EndpointMap, KeystoneInternal, uri_no_suffix]
        cinder_volume: &cinder_barbican_config
          cinder::config::cinder_config:
            key_manager/backend:
              value: barbican
            barbican/barbican_endpoint:
              value: {get_param: [EndpointMap, BarbicanInternal, uri]}
            barbican/auth_endpoint:
              value: {get_param: [EndpointMap, KeystoneInternal, uri_no_suffix]}
        cinder_backup: *cinder_barbican_config
        glance_api: &glance_barbican_config
          glance::api::keymgr_backend: barbican
          glance::api::keymgr_encryption_api_url:
            get_param: [EndpointMap, BarbicanInternal, uri]
          glance::api::keymgr_encryption_auth_url:
            get_param: [EndpointMap, KeystoneInternal, uri_no_suffix]
        glance_api_edge: *glance_barbican_config
